#!/usr/bin/env bash
# Single-source-of-truth guard for the backend<->client taxonomy contract.
#
# Backend/functions/coaching/taxonomy.json is authoritative.
# The client's bundled copy is GENERATED by this script, never hand-edited -
# byte-drift between the two is exactly the failure mode a "bundled synced
# copy" is supposed to prevent.
#
# Modes:
#   (default)  sync: copy the source over each client destination. Run
#              locally after editing the backend taxonomy.
#   --check    drift guard: diff WITHOUT copying, exit 1 on any mismatch.
#              Run in CI on every push - a hand-edit to either bundled
#              client copy fails the build instead of shipping undetected.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SOURCE="$REPO_ROOT/Backend/functions/coaching/taxonomy.json"
DESTS=(
  "$REPO_ROOT/BanterApp/Resources/taxonomy.json"
  "$REPO_ROOT/BanterShared/Sources/BanterShared/Resources/taxonomy.json"
  "$REPO_ROOT/web/src/lib/taxonomy.json"
)

CHECK_ONLY=false
if [ "${1:-}" = "--check" ]; then
  CHECK_ONLY=true
fi

if [ ! -f "$SOURCE" ]; then
  echo "sync-taxonomy.sh: source taxonomy not found at $SOURCE" >&2
  exit 1
fi

for DEST in "${DESTS[@]}"; do
  if [ "$CHECK_ONLY" = true ]; then
    if [ ! -f "$DEST" ]; then
      echo "sync-taxonomy.sh: DRIFT - $DEST is missing. Run Backend/scripts/sync-taxonomy.sh to regenerate." >&2
      exit 1
    fi
    if ! diff -u "$SOURCE" "$DEST"; then
      echo "sync-taxonomy.sh: DRIFT - $DEST differs from $SOURCE. Run Backend/scripts/sync-taxonomy.sh (never hand-edit the client copy)." >&2
      exit 1
    fi
  else
    mkdir -p "$(dirname "$DEST")"
    cp "$SOURCE" "$DEST"
  fi
done

if [ "$CHECK_ONLY" = true ]; then
  echo "sync-taxonomy.sh: taxonomy files byte-identical ($SOURCE <-> ${DESTS[*]})"
else
  echo "sync-taxonomy.sh: synced $SOURCE -> ${DESTS[*]}"
fi
