#!/usr/bin/env bash
# Single-source-of-truth guard for the Deno<->Swift shared contract fixture.
#
# Backend/tests/fixtures/coaching-response.sample.json is authoritative.
# The Swift copy is GENERATED by this script, never hand-edited - byte-drift
# between the two is exactly the failure mode a "shared fixture" is supposed
# to prevent. Run locally after editing the Deno fixture, and in CI
# (backend-tests job) as a drift guard on every push.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SOURCE="$REPO_ROOT/Backend/tests/fixtures/coaching-response.sample.json"
DEST="$REPO_ROOT/BanterShared/Tests/BanterSharedTests/Fixtures/coaching-response.sample.json"

if [ ! -f "$SOURCE" ]; then
  echo "sync-fixture.sh: source fixture not found at $SOURCE" >&2
  exit 1
fi

mkdir -p "$(dirname "$DEST")"
cp "$SOURCE" "$DEST"

if ! diff -q "$SOURCE" "$DEST" > /dev/null; then
  echo "sync-fixture.sh: fixtures differ after copy - this should never happen" >&2
  diff "$SOURCE" "$DEST" >&2 || true
  exit 1
fi

echo "sync-fixture.sh: fixtures byte-identical ($SOURCE <-> $DEST)"
