#!/usr/bin/env bash
# Single-source-of-truth guard for the backend<->client taxonomy contract.
#
# Backend/functions/coaching/taxonomy.json is authoritative.
# The client's bundled copy is GENERATED by this script, never hand-edited -
# byte-drift between the two is exactly the failure mode a "bundled synced
# copy" is supposed to prevent. Run locally after editing the backend
# taxonomy, and in CI as a drift guard on every push.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SOURCE="$REPO_ROOT/Backend/functions/coaching/taxonomy.json"
DESTS=(
  "$REPO_ROOT/BanterApp/Resources/taxonomy.json"
  "$REPO_ROOT/BanterShared/Sources/BanterShared/Resources/taxonomy.json"
)

if [ ! -f "$SOURCE" ]; then
  echo "sync-taxonomy.sh: source taxonomy not found at $SOURCE" >&2
  exit 1
fi

for DEST in "${DESTS[@]}"; do
  mkdir -p "$(dirname "$DEST")"
  cp "$SOURCE" "$DEST"

  if ! diff -q "$SOURCE" "$DEST" > /dev/null; then
    echo "sync-taxonomy.sh: taxonomy files differ after copy - this should never happen" >&2
    diff "$SOURCE" "$DEST" >&2 || true
    exit 1
  fi
done

echo "sync-taxonomy.sh: taxonomy files byte-identical ($SOURCE <-> ${DESTS[*]})"
